openapi: 3.0.0
info:
  title: Example API - Project B
  version: 1.0.0
  description: Example OpenAPI specification for Project B

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /tasks:
    get:
      summary: Get tasks
      description: Retrieve a list of tasks
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    status:
                      type: string
