openapi: 3.0.0
info:
  title: Example API - Project A
  version: 1.0.0
  description: Example OpenAPI specification for Project A

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /users:
    get:
      summary: Get users
      description: Retrieve a list of users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
